# Generated by Django 5.0.2 on 2024-08-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_authenticated',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(),
        ),
    ]
