# Generated by Django 5.0.2 on 2024-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddl', '0003_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='join_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='join_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
