# Generated by Django 5.0.2 on 2024-08-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huddl', '0004_club_join_enabled_club_join_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
