# Generated by Django 5.0.2 on 2024-08-17 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddl', '0005_delete_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_budget_limit',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='default_max_time',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
