# Generated by Django 5.0.2 on 2024-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='join_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
