# Generated by Django 5.0.2 on 2024-08-18 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_clubprofile_club_alter_clubprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='FinalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_in', to='club.activity')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_plan', to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='VotingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_plan', to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_min', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost_max', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_made', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='club.votingplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='finalplan',
            constraint=models.UniqueConstraint(fields=('club',), name='one-plan-per-club'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('plan', 'user'), name='one-vote-per-user'),
        ),
    ]
