# Generated by Django 5.0.2 on 2024-08-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_description_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='finalplan',
            name='one-plan-per-club',
        ),
        migrations.AlterField(
            model_name='finalplan',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_plan', to='club.club', unique=True),
        ),
        migrations.AlterField(
            model_name='votingplan',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_plan', to='club.club', unique=True),
        ),
    ]
