# Generated by Django 5.0.2 on 2024-08-18 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_remove_finalplan_one_plan_per_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalplan',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_plan', to='club.club'),
        ),
        migrations.AlterField(
            model_name='votingplan',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_plan', to='club.club'),
        ),
    ]
