# Generated by Django 5.0.2 on 2024-08-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_alter_finalplan_club_alter_votingplan_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingplan',
            name='club',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='VotingPlan',
        ),
    ]
