# Generated by Django 5.0.2 on 2024-08-18 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_remove_votingplan_club_delete_vote_delete_votingplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalplan',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_plans', to='club.club'),
        ),
    ]
