# Generated by Django 5.0.2 on 2024-08-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_finalplan_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
